// Template Processing - Dynamic Rounding
// Randomized number and rounding place generated by template processing,
// with the correct answer computed from the template variables

export const name = "Template Processing - Dynamic Rounding";

export const item = `<?xml version="1.0" encoding="UTF-8"?>
<qti-assessment-item xmlns="http://www.imsglobal.org/xsd/imsqtiasi_v3p0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsglobal.org/xsd/imsqtiasi_v3p0 https://purl.imsglobal.org/spec/qti/v3p0/schema/xsd/imsqti_asiv3p0p1_v1p0.xsd"
    identifier="dynamic-rounding" title="Dynamic Number Rounding" adaptive="false"
    time-dependent="false" xml:lang="en">

    <qti-response-declaration identifier="RESPONSE" cardinality="single" base-type="integer"/>

    <qti-outcome-declaration identifier="SCORE" cardinality="single" base-type="float">
        <qti-default-value>
            <qti-value>0</qti-value>
        </qti-default-value>
    </qti-outcome-declaration>
    <qti-outcome-declaration identifier="MAXSCORE" cardinality="single" base-type="float">
        <qti-default-value>
            <qti-value>1.0</qti-value>
        </qti-default-value>
    </qti-outcome-declaration>
    <qti-outcome-declaration identifier="FEEDBACK" cardinality="multiple" base-type="identifier"/>

    <!-- The number to be rounded, generated once per attempt -->
    <qti-template-declaration identifier="X" cardinality="single" base-type="integer"/>

    <!-- What to round to (10 or 100), selected randomly -->
    <qti-template-declaration identifier="ROUND_TO" cardinality="single" base-type="integer"/>

    <!-- The calculated correct answer -->
    <qti-template-declaration identifier="ANSWER" cardinality="single" base-type="integer"/>

    <qti-template-processing>
        <qti-set-template-value identifier="X">
            <qti-random-integer min="101" max="999"/>
        </qti-set-template-value>
        <qti-set-template-value identifier="ROUND_TO">
            <qti-random>
                <qti-multiple>
                    <qti-base-value base-type="integer">10</qti-base-value>
                    <qti-base-value base-type="integer">100</qti-base-value>
                </qti-multiple>
            </qti-random>
        </qti-set-template-value>
        <!-- The formula for rounding X to the nearest N is round(X/N) * N -->
        <qti-set-template-value identifier="ANSWER">
            <qti-product>
                <qti-round>
                    <qti-divide>
                        <qti-variable identifier="X"/>
                        <qti-variable identifier="ROUND_TO"/>
                    </qti-divide>
                </qti-round>
                <qti-variable identifier="ROUND_TO"/>
            </qti-product>
        </qti-set-template-value>
    </qti-template-processing>

    <qti-item-body>
        <p>Round the number <qti-printed-variable identifier="X"/> to the nearest
                <qti-printed-variable identifier="ROUND_TO"/>.</p>
        <p>Your answer: <qti-text-entry-interaction response-identifier="RESPONSE" expected-length="10"
                pattern-mask="[0-9]{1,4}"
                data-patternmask-message="Please enter a whole number."/></p>

        <qti-feedback-block outcome-identifier="FEEDBACK" identifier="CORRECT" show-hide="show"
            data-feedback-type="correct">
            <p><strong>Correct!</strong> <qti-printed-variable identifier="X"/> rounded to the
                nearest <qti-printed-variable identifier="ROUND_TO"/> is indeed
                    <qti-printed-variable identifier="ANSWER"/>.</p>
        </qti-feedback-block>
        <qti-feedback-block outcome-identifier="FEEDBACK" identifier="INCORRECT" show-hide="show"
            data-feedback-type="incorrect">
            <p><strong>Incorrect.</strong> The correct answer is <qti-printed-variable
                    identifier="ANSWER"/>.</p>
            <p>To round a number, look at the digit to the right of the place you are rounding to.
                If the digit is 5 or more, you round up. If it is 4 or less, you round down (keep
                the digit the same). All digits to the right of the rounded digit become zero.</p>
        </qti-feedback-block>
    </qti-item-body>

    <qti-response-processing>
        <qti-response-condition>
            <qti-response-if>
                <qti-equal>
                    <qti-variable identifier="RESPONSE"/>
                    <qti-variable identifier="ANSWER"/>
                </qti-equal>
                <qti-set-outcome-value identifier="SCORE">
                    <qti-base-value base-type="float">1</qti-base-value>
                </qti-set-outcome-value>
                <qti-set-outcome-value identifier="FEEDBACK">
                    <qti-multiple>
                        <qti-base-value base-type="identifier">CORRECT</qti-base-value>
                    </qti-multiple>
                </qti-set-outcome-value>
            </qti-response-if>
            <qti-response-else>
                <qti-set-outcome-value identifier="SCORE">
                    <qti-base-value base-type="float">0</qti-base-value>
                </qti-set-outcome-value>
                <qti-set-outcome-value identifier="FEEDBACK">
                    <qti-multiple>
                        <qti-base-value base-type="identifier">INCORRECT</qti-base-value>
                    </qti-multiple>
                </qti-set-outcome-value>
            </qti-response-else>
        </qti-response-condition>
    </qti-response-processing>
</qti-assessment-item>`;

export const interactionTypes: string[] = ['text-entry'];
